/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: UmangRank (https://sketchfab.com/UmangRank)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sushi-4012e8f4e2b4427c8334057a02b237ef
Title: Sushi
*/

import * as THREE from "three";
import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    mesh_base_material_0: THREE.Mesh;
  };
  materials: {
    base_material: THREE.MeshStandardMaterial;
  };
};

export function SushiModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/sushi.glb"
  ) as unknown as GLTFResult;
  const meshRef = useRef<THREE.Mesh>(null);
  useFrame((state, delta) => (meshRef.current!.rotation.y += delta * 0.5));
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_base_material_0.geometry}
          material={materials.base_material}
          scale={170.896}
          ref={meshRef}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/sushi.glb");
